# .streamlit/config.toml

[theme]
base="light" # Tema di base chiaro
primaryColor="#4CAF50" # Un bel verde per gli elementi primari (es. bottoni, slider)
backgroundColor="#FFFFFF" # Sfondo principale (bianco)
secondaryBackgroundColor="#F0F2F6" # Sfondo per sidebar e sezioni (grigio chiaro)
textColor="#333333" # Colore del testo principale (grigio scuro)
font="sans serif" # Font di base (Streamlit cercherà di usare Inter se disponibile)

# Configurazione per i grafici Matplotlib (per il tema chiaro)
[matplotlib]
use_dark_background=false
